### ISSUE TITLE
 ERROR o.e.kafka.indexer.MessageHandler - Failed Message #1, REST response:TOO_MANY_REQUESTS

### ISSUE THREAD

**Issue by zousheng** [reachkrishnaraj/kafka-elasticsearch-standalone-consumer#31]
Hi team,

Today I found some error message in the project log (we had 500 partition defined in the kafka, so there are 500 threads), I tried to find the error in the code, unfortunately got nothing, would you please give some advice on this? thanks

2016:10:21:05:055 +0800 [kafka-indexer-consumer-thread-165] ERROR o.e.kafka.indexer.MessageHandler - Failed Message #1, REST response:TOO_MANY_REQUESTS; errorMessage:EsRejectedExecutionException[rejected execution (queue capacity 50) on org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1@15b1e524]
12/四月/2016:10:21:04:013 +0800 [kafka-indexer-consumer-thread-197] INFO  o.e.kafka.indexer.MessageHandler - Total # of messages in this batch: 2; # of successfully transformed and added to Index messages: 2; offsetOfNextBatch: 238952

**Comment by ppine7** [comment]
Hi, Zousheng,

We saw this type of errors too - when we were sending too many parallel indexing requests to ES. This is an error response from ES itself, when it cannot execute requests fast enough and cannot queue them up due to queues being full. You need to adjust your ES config settings, in particular pool sizes: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html

We ended up increasing the threadpool sizes for "bulk" (from default 50 to 500) and "search" (to 3000) operations

**Comment by zousheng** [comment]
Hi ppine7, thanks very much for your quick favor, really appreciate it, I already change the threadpool sizes. Cheers!

BRs
